services:
  db:
    image: postgres:17
    container_name: desafio_votacao_db
    environment:
      POSTGRES_DB: desafio_votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: ./backend
    container_name: desafio_votacao_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/desafio_votacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always

volumes:
  pgdata:
